### ISSUE TITLE
File Access Exception

### ISSUE THREAD

**Issue by GamingAnonymous** [BeardlessDev/Twitch-Dev-Company#28]
**Bug/Feature/Improvement?**
Bug

**Short Description**
If you try to save to the same file many times at once, It will throw an exception.

**Suggested Changes/Implementation**
Instead of saving when something changes or a message is received you should use some sort of timer to save at a set interval. Using Coroutine/Timer or something similar.

**Comment by BeardlessDev** [comment]
We save every minute and if you quit the application, we do an emergency save in case anything has changed since the last save.
